---
language: ruby

sudo: false

cache: bundler

script:
  - 'SPEC_OPTS="--format documentation" bundle exec rake spec'

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.3.1

matrix:
  fast_finish: true

deploy:
  provider: rubygems
  api_key:
    secure: ""
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true

notifications:
  email: false
